version: '3'
services:
  backend:
    build: .
    container_name: nest-backend
    ports:
      - "3000:3000"
    networks:
      - backend_network
    environment:
      - NODE_ENV=production

networks:
  backend_network:
    driver: bridge
